<?php
/**
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright Copyright (c) 2018 MagedIn. (http://www.magedin.com)
 *
 * @author    Bruno Gemelli <bruno.gemelli@magedin.com>
 */

namespace MagedIn\Frenet\Model\Shipping;

use Magento\Framework\Module\Dir;
use Magento\Framework\Xml\Security;
use Magento\Quote\Model\Quote\Address\RateRequest;
use Magento\Setup\Exception;
use Magento\Shipping\Model\Rate\Result;

class Carrier extends \Magento\Shipping\Model\Carrier\AbstractCarrierOnline
    implements \Magento\Shipping\Model\Carrier\CarrierInterface
{
    /**
     * Code of the carrier
     *
     * @var string
     */
    protected $_code = 'magedinfrenet';

    /**
     * Rate result data
     *
     * @var Result|null
     */
    protected $_result = null;

    /**
     * @var \Magento\Catalog\Model\ProductRepository
     */
    protected $_productRepository;

    /**
     * @var \Magento\Framework\HTTP\ZendClientFactory
     */
    protected $_zendClientFactory;

    /**
     * @var \Magento\Shipping\Model\Rate\ResultFactory
     */
    protected $_rateFactory;


    /**
     * Carrier constructor.
     *
     * @param \Magento\Catalog\Model\ProductRepository $productRepository
     * @param \Magento\Framework\HTTP\ZendClientFactory $zendClientFactory
     * @param \Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig
     * @param \Magento\Quote\Model\Quote\Address\RateResult\ErrorFactory $rateErrorFactory
     * @param \Psr\Log\LoggerInterface $logger
     * @param Security $xmlSecurity
     * @param \Magento\Shipping\Model\Simplexml\ElementFactory $xmlElFactory
     * @param \Magento\Shipping\Model\Rate\ResultFactory $rateFactory
     * @param \Magento\Quote\Model\Quote\Address\RateResult\MethodFactory $rateMethodFactory
     * @param \Magento\Shipping\Model\Tracking\ResultFactory $trackFactory
     * @param \Magento\Shipping\Model\Tracking\Result\ErrorFactory $trackErrorFactory
     * @param \Magento\Shipping\Model\Tracking\Result\StatusFactory $trackStatusFactory
     * @param \Magento\Directory\Model\RegionFactory $regionFactory
     * @param \Magento\Directory\Model\CountryFactory $countryFactory
     * @param \Magento\Directory\Model\CurrencyFactory $currencyFactory
     * @param \Magento\Directory\Helper\Data $directoryData
     * @param \Magento\CatalogInventory\Api\StockRegistryInterface $stockRegistry
     * @param Dir\Reader $configReader
     * @param \Magento\Catalog\Model\ResourceModel\Product\CollectionFactory $productCollectionFactory
     * @param array $data
     */
    public function __construct(
        \Magento\Catalog\Model\ProductRepository $productRepository,
        \Magento\Framework\HTTP\ZendClientFactory $zendClientFactory,
        \Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig,
        \Magento\Quote\Model\Quote\Address\RateResult\ErrorFactory $rateErrorFactory,
        \Psr\Log\LoggerInterface $logger,
        Security $xmlSecurity,
        \Magento\Shipping\Model\Simplexml\ElementFactory $xmlElFactory,
        \Magento\Shipping\Model\Rate\ResultFactory $rateFactory,
        \Magento\Quote\Model\Quote\Address\RateResult\MethodFactory $rateMethodFactory,
        \Magento\Shipping\Model\Tracking\ResultFactory $trackFactory,
        \Magento\Shipping\Model\Tracking\Result\ErrorFactory $trackErrorFactory,
        \Magento\Shipping\Model\Tracking\Result\StatusFactory $trackStatusFactory,
        \Magento\Directory\Model\RegionFactory $regionFactory,
        \Magento\Directory\Model\CountryFactory $countryFactory,
        \Magento\Directory\Model\CurrencyFactory $currencyFactory,
        \Magento\Directory\Helper\Data $directoryData,
        \Magento\CatalogInventory\Api\StockRegistryInterface $stockRegistry,
        \Magento\Framework\Module\Dir\Reader $configReader,
        \Magento\Catalog\Model\ResourceModel\Product\CollectionFactory $productCollectionFactory,
        array $data = []
    ) {
        $this->_productRepository = $productRepository;
        $this->_zendClientFactory = $zendClientFactory;
        $this->_rateFactory       = $rateFactory;

        parent::__construct(
            $scopeConfig,
            $rateErrorFactory,
            $logger,
            $xmlSecurity,
            $xmlElFactory,
            $rateFactory,
            $rateMethodFactory,
            $trackFactory,
            $trackErrorFactory,
            $trackStatusFactory,
            $regionFactory,
            $countryFactory,
            $currencyFactory,
            $directoryData,
            $stockRegistry,
            $data
        );
    }


    /**
     * Processing additional validation to check if carrier applicable.
     *
     * @param \Magento\Framework\DataObject $request
     * @return $this|bool|\Magento\Framework\DataObject
     */
    public function proccessAdditionalValidation(\Magento\Framework\DataObject $request)
    {
        /**
         * @todo logic
         * verify: quote items, destination postcode, origin postcode, Frenet Token, etc...
         */

        return $this;
    }


    /**
     * @param RateRequest $request
     * @return bool|\Magento\Framework\DataObject|\Magento\Quote\Model\Quote\Address\RateResult\Error|Result|null
     * @throws \Magento\Framework\Exception\NoSuchEntityException
     */
    public function collectRates(RateRequest $request)
    {
        if (!$this->canCollectRates()) {
            return $this->getErrorMessage();
        }

        $this->_prepareRequest($request);
        $this->_getQuotes();

        return $this->_result;
    }


    /**
     * @todo refactor this method (move to a separated class), get dynamic data and improve logic
     *
     * @param $request
     * @throws \Magento\Framework\Exception\NoSuchEntityException
     */
    protected function _prepareRequest($request)
    {
        $items       = [];
        $totalAmount = 0;

        /** @var \Magento\Quote\Api\Data\CartItemInterface $item */
        foreach ($request->getAllItems() as $item) {

            /**
             * Skip bundle and configurable product types
             */
            if ($item->getProductType() != \Magento\Catalog\Model\Product\Type::TYPE_SIMPLE) {
                continue;
            }

            $hasParent = ($item->getParentItemId()) ? true : false;

            $product        = $this->_productRepository->getById($item->getProductId());
            $parentProduct  = null;

            if ($hasParent) {
                $parentProduct        = $this->_productRepository->getById($item->getParentItem()->getProductId());
            }

            $items[] = [
                'Weight'    => $product->getWeight(),
                'Length'    => ($hasParent) ? $product->getData('ts_dimensions_length') : $product->getData('ts_dimensions_length'),
                'Height'    => ($hasParent) ? $product->getData('ts_dimensions_height') : $product->getData('ts_dimensions_height'),
                'Width'     => ($hasParent) ? $product->getData('ts_dimensions_width') : $product->getData('ts_dimensions_width'),
                'Quantity'  => ($hasParent) ? $item->getParentItem()->getQty() : $item->getQty(),
            ];

            $totalAmount += $item->getQty() * $item->getPrice();
        }

        $apiRequest = [
            'SellerCEP'             => '04601001',
            'RecipientCEP'          => '95010510',
            'ShipmentInvoiceValue'  => $totalAmount,
            'ShippingItemArray'     => $items,
        ];

        $this->setRequest($request);
        $this->setApiRequest($apiRequest);
    }

    /**
     * ???
     * @todo
     *
     * @return Result
     * @throws \Zend_Http_Client_Exception
     */
    protected function _getQuotes()
    {
        try {
            $apiResults = $this->_getApiResults();

            /** @var \Magento\Shipping\Model\Rate\Result $result */
            $result = $this->_rateFactory->create();

            foreach ($apiResults as $apiResult) {
                $method = $this->_rateMethodFactory->create();
                $method->setCarrier($this->_code);
                $method->setCarrierTitle('');
                $method->setMethod($apiResult->Carrier.''.$apiResult->ServiceDescription);
                $method->setMethodTitle($apiResult->Carrier.' - '.$apiResult->ServiceDescription);
                $method->setPrice($apiResult->ShippingPrice);
                $method->setCost($apiResult->ShippingPrice);
                $result->append($method);
            }

        } catch (Exception $e) {
            $a = 1;
        }

        $this->_result = $result;

        return $result;
    }


    /**
     * ?????
     * @todo
     *
     * @return object
     * @throws \Zend_Http_Client_Exception
     */
    protected function _getApiResults()
    {
        /** @var \Magento\Framework\HTTP\ZendClient $client */
        $client = $this->_zendClientFactory->create();

        $client->setUri('http://api.frenet.com.br/shipping/quote');
        $client->setMethod(\Zend_Http_Client::POST);
        $client->setRawData(json_encode($this->getApiRequest()), 'application/json');
        $client->setHeaders(
            [
                'Content-Type' => 'application/json',
                'token'        => '405D6786RC542R4AD2RA994R3177D4EFF2BD'
            ]
        );
        $client->setUrlEncodeBody(false);

        $response = $client->request();

        if (!$response->isSuccessful()) {
            //thow exception
        }

        //@todo log??

        $bodyResponse = json_decode($response->getBody());

        return $bodyResponse->ShippingSevicesArray;
    }


    /**
     * @param \Magento\Framework\DataObject $request
     *
     * @return \Magento\Framework\DataObject|null
     */
    protected function _doShipmentRequest(\Magento\Framework\DataObject $request)
    {
        return null;
    }


    /**
     * @return array
     */
    public function getAllowedMethods()
    {
        return [$this->_code => $this->getConfigData ('title')];
    }
}