<?php
/**
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright Copyright (c) 2018 MagedIn. (http://www.magedin.com)
 *
 * @author    Bruno Gemelli <bruno.gemelli@magedin.com>
 * @author    Tiago Sampaio <tiago.sampaio@magedin.com>
 */

namespace MagedIn\Frenet\Api;

interface CategoryRepositoryInterface
{

    /**
     * @param \Magento\Catalog\Api\Data\ProductInterface $product
     * 
     * @return string
     */
    public function getCategories(\Magento\Catalog\Api\Data\ProductInterface $product);
}
