<?php
/**
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright Copyright (c) 2018 MagedIn. (http://www.magedin.com)
 *
 * @author    Bruno Gemelli <bruno.gemelli@magedin.com>
 */

namespace MagedIn\Frenet\Api;

interface ProductRepositoryInterface
{

/**
     * @param \Magento\Quote\Api\Data\CartItemInterface $item
     * 
     * @return array
     */
    public function getShippingItem($item);

    public function setDefault($use_default, $default_length, $default_width, $default_height, $default_weight, $weight_type);
}