<?php
/**
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright Copyright (c) 2018 MagedIn. (http://www.magedin.com)
 *
 * @author    Bruno Gemelli <bruno.gemelli@magedin.com>
 */

namespace MagedIn\Frenet\Api;

interface ServiceRepositoryInterface
{

    public function getShippingQuote(\Magento\Quote\Model\Quote\Address\RateRequest $rateRequest);
}
